add_newline = false

format = "$directory$git_branch$git_status$kubernetes$character"

[directory]
format = "  [$path]($style)[$read_only]($read_only_style) "

[kubernetes]
disabled = false

[gcloud]
disabled = true
